name: Build Archivematica MCP Client Docker Image

on:
  push:
    branches:
      - main
      - qa/1.x

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        file: hack/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          olivergra/archivematica-mcp-client:latest
        build-args: |
          TARGET=archivematica-mcp-client
          USER_ID=1000
          GROUP_ID=1000
          UBUNTU_VERSION=22.04
          PYTHON_VERSION=3.9
